name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - '!chart/backstage/templates/README.md'

jobs:
  release:
    permissions:
      contents: write # needed to write releases
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: latest

      # - name: Prepare keys for signing
      #   env:
      #     SIGNING_KEY_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY }}
      #     SIGNING_KEY_PASSPHRASE_BASE64: ${{ secrets.HELM_SIGNING_PRIVATE_KEY_PASSPHRASE }}
      #     KEY_PATH: ".gpg-dir"
      #     SIGNING_KEY_PATH: ".gpg-dir/secring.gpg"
      #     SIGNING_KEY_PASSPHRASE_PATH: ".gpg-dir/passphrase"
      #   run: |
      #     mkdir "$KEY_PATH"
      #     base64 -d <<< "$SIGNING_KEY_BASE64" > "$SIGNING_KEY_PATH"
      #     base64 -d <<< "$SIGNING_KEY_PASSPHRASE_BASE64" > "$SIGNING_KEY_PASSPHRASE_PATH"
      #     echo "CR_PASSPHRASE_FILE=$SIGNING_KEY_PASSPHRASE_PATH" >> "$GITHUB_ENV"
      #     echo "CR_KEYRING=$SIGNING_KEY_PATH" >> "$GITHUB_ENV"

      - name: Prepare GPG key
        run: |
          gpg_dir=.cr-gpg
          mkdir "$gpg_dir"
          keyring="$gpg_dir/secring.gpg"
          base64 -d <<< "$HELM_SIGNING_PRIVATE_KEY" > "$keyring"
          passphrase_file="$gpg_dir/passphrase"
          echo "$HELM_SIGNING_PRIVATE_KEY_PASSPHRASE" > "$passphrase_file"
          echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
          echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
        env:
          GPG_KEYRING_BASE64: "${{ secrets.HELM_SIGNING_PRIVATE_KEY }}"
          GPG_PASSPHRASE: "${{ secrets.HELM_SIGNING_PRIVATE_KEY_PASSPHRASE }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 #v1.5.0
        with:
          charts_dir: chart
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
